
# tap repositories and their packages

tap homebrew/core
brew act
brew ansible
brew aom
brew aribb24
brew autoconf
brew awscli
brew bat
brew bitrise
brew boost
brew brotli
brew ca-certificates
brew cairo
brew certifi
brew cffi
brew chezmoi
brew cjson
brew cocoapods
brew confuse
brew cryptography
brew dav1d
brew dfu-util
brew diff-so-fancy
brew dnsmasq
brew doctl
brew docutils
brew double-conversion
brew edencommon
brew fastlane
brew fb303
brew fbthrift
brew fd
brew ffmpeg
brew fizz
brew flac
brew fmt
brew folly
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fswatch
brew fzf
brew gdk-pixbuf
brew geckodriver
brew gettext
brew gflags
brew gh
brew ghostscript
brew giflib
brew git
brew git-delta
brew git-filter-repo
brew git-lfs
brew glances
brew glib
brew glog
brew glow
brew gmp
brew gnutls
brew gradle
brew graphite2
brew harfbuzz
brew highway
brew homeassistant-cli
brew htop
brew hub
brew icu4c@76
brew imagemagick
brew imath
brew ios-deploy
brew iperf
brew iperf3
brew jasper
brew jbig2dec
brew jpeg
brew jpeg-turbo
brew jpeg-xl
brew jq
brew krb5
brew lame
brew lazygit
brew leptonica
brew libarchive
brew libass
brew libb2
brew libbluray
brew libde265
brew libdeflate
brew libevent
brew libgit2
brew libheif
brew libidn
brew libidn2
brew liblo
brew liblqr
brew libmicrohttpd
brew libmonome
brew libnghttp2
brew libogg
brew libomp
brew libpng
brew libraw
brew librist
brew librsvg
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew llvm
brew lpeg
brew luajit
brew luv
brew lz4
brew lzo
brew m4
brew mas
brew mbedtls
brew mcfly
brew mkcert
brew mpdecimal
brew mpg123
brew msgpack
brew mvfst
brew ncurses
brew neovim
brew nettle
brew node-build
brew nspr
brew nss
brew oniguruma
brew opencore-amr
brew openexr
brew openjdk
brew openjpeg
brew openssl@3
brew opus
brew p11-kit
brew pango
brew pcre2
brew pipx
brew pixman
brew pkgconf
brew pnpm
brew portaudio
brew postgresql@14
brew powerlevel10k
brew pycparser
brew pyenv
brew python-packaging
brew python@3.12
brew python@3.13
brew rav1e
brew readline
brew ripgrep
brew rubberband
brew ruby
brew sdl2
brew serialosc
brew shared-mime-info
brew snappy
brew speex
brew sqlite
brew srt
brew starship
brew svt-av1
brew terminal-notifier
brew tesseract
brew theora
brew tree-sitter
brew unbound
brew unibilium
brew uv
brew wangle
brew watchman
brew webp
brew wget
brew x264
brew x265
brew xdg-ninja --HEAD
brew xorgproto
brew xvid
brew xxhash
brew xz
brew yq
brew z3
brew zeromq
brew zimg
brew zsh
brew zsh-autosuggestions
brew zstd

tap homebrew/cask
cask 1password
cask 1password-cli
cask alt-tab
cask expo-orbit
cask firefox
cask font-cascadia-code
cask font-fira-code
cask font-jetbrains-mono
cask font-meslo-lg-nerd-font
cask homerow
cask karabiner-elements
cask macupdater
cask postman
cask react-native-debugger
cask zulu@17

tap homebrew/bundle

tap homebrew/services

tap olets/tap
brew olets/tap/zsh-abbr

tap qovery/replibyte
brew qovery/replibyte/replibyte

tap rcmdnk/file
brew rcmdnk/file/brew-file

tap withgraphite/tap
brew withgraphite/tap/graphite

# App Store applications
appstore 1569813296 1Password for Safari (8.10.64)
appstore 1402042596 AdBlock (2.1.10)
appstore 1616822987 Affinity Photo 2 (2.6.0)
appstore 302584613 Amazon Kindle (7.27)
appstore 1586841361 Animoog Z (1.2.1)
appstore 1037126344 Apple Configurator (2.17)
appstore 425264550 Blackmagic Disk Speed Test (3.4.2)
appstore 1500855883 CapCut (5.7.1)
appstore 696977615 Capo (4.3.9)
appstore 424390742 Compressor (4.9)
appstore 1320450034 DaftCloud (4.1.6)
appstore 1055511498 Day One (2025.5)
appstore 640199958 Developer (10.7.1)
appstore 450527929 djay Pro (5.2.9)
appstore 975937182 Fantastical (4.0.5)
appstore 424389933 Final Cut Pro (11.0.1)
appstore 363738376 forScore (14.3.4)
appstore 682658836 GarageBand (10.4.12)
appstore 1099568401 Home Assistant (2025.2)
appstore 967004861 HP Easy Scan (2.0.0)
appstore 1500678169 Hue Menu (2.7.8)
appstore 408981434 iMovie (10.4.3)
appstore 288545208 Instapaper (9.1.1)
appstore 1319778037 iStat Menus (6.73)
appstore 470158793 Keka (1.4.7)
appstore 409183694 Keynote (14.3)
appstore 405399194 Kindle (1.40.3)
appstore 414030210 LimeChat (2.47)
appstore 634148309 Logic Pro (11.1.2)
appstore 441258766 Magnet (3.0.6)
appstore 1480068668 Messenger (232.4)
appstore 1629209970 Metronome (1.4)
appstore 985367838 Microsoft Outlook (16.94.2)
appstore 1339418001 Model D (1.5.1)
appstore 419330170 Moom Classic (3.2.28)
appstore 1527105121 Neural Mix Pro (2.0.2)
appstore 409203825 Numbers (14.3)
appstore 409201541 Pages (14.3)
appstore 6714467650 Perplexity (1.0.16)
appstore 1006401965 Samplism Lite (1.3.10)
appstore 442168834 SiteSucker (5.6.1)
appstore 1376402589 StopTheMadness (41.3)
appstore 1087079310 Switch Sound File Converter (13.00)
appstore 1475387142 Tailscale (1.80.2)
appstore 1533078079 Teleprompter (3.9.25)
appstore 899247664 TestFlight (3.7.1)
appstore 1528890965 TextSniper (1.11.0)
appstore 904280696 Things3 (3.21.5)
appstore 1291898086 Toggl Track (10.8.0)
appstore 1263858588 Tonebridge Guitar Effects (1.4.1)
appstore 1436522307 Transmit (5.10.8)
appstore 1278508951 Trello (2.15.7)
appstore 1480933944 Vimari (2.1.1)
appstore 1598483936 Virtual Teleprompter Lite (1.0.14)
appstore 1591588588 Virtual Teleprompter Pro (1.0.32)
appstore 310633997 WhatsApp (25.4.75)
appstore 497799835 Xcode (16.2)
appstore 889428659 xScope (4.7.1)
